### ISSUE TITLE
crazy errors about multiprocessing spawn in Win10 using python 3.7

### ISSUE THREAD

**Issue by b0b5h4rp13** [thombashi/SimpleSQLite#65]
When I run the above code from your example I get the following errors on Win 10 with Python 3.7:

from simplesqlite import SimpleSQLite
import pandas

con = SimpleSQLite("pandas_df.sqlite")

con.create_table_from_dataframe(pandas.DataFrame(
    [
        [0, 0.1, "a"],
        [1, 1.1, "bb"],
        [2, 2.2, "ccc"],
    ],
    columns=['id', 'value', 'name']
), table_name="pandas_df")

---------------------- errors ------------------------

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\pycharm\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\pycharm\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\pycharm\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\pycharm\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\pycharm\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\pycharm\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\pycharm\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "E:\pycharm\webull\venv\apps\cache test.py", line 8, in <module>
    sql.create_table_from_dataframe(data1, table_name='data1')
  File "E:\pycharm\webull\venv\lib\site-packages\simplesqlite\core.py", line 1526, in create_table_from_dataframe
    index_attrs,
  File "E:\pycharm\webull\venv\lib\site-packages\simplesqlite\core.py", line 1714, in __create_table_from_tabledata
    table_data, primary_key, add_primary_key_column
  File "E:\pycharm\webull\venv\lib\site-packages\simplesqlite\core.py", line 1659, in __extract_attr_descs_from_tabledata
    for col, value_type in sorted(self.__extract_col_type_from_tabledata(table_data).items()):
  File "E:\pycharm\webull\venv\lib\site-packages\simplesqlite\core.py", line 1687, in __extract_col_type_from_tabledata
    for col_idx, col_dp in enumerate(table_data.column_dp_list)
  File "E:\pycharm\webull\venv\lib\site-packages\tabledata\_core.py", line 190, in column_dp_list
    return self.__dp_extractor.to_column_dp_list(self.value_dp_matrix)
  File "E:\pycharm\webull\venv\lib\site-packages\tabledata\_core.py", line 179, in value_dp_matrix
    to_value_matrix(self.headers, self.rows)
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 453, in to_dp_matrix
    return self.__to_dp_matrix_mt(value_matrix)
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 588, in __to_dp_matrix_mt
    for col_idx, values in enumerate(zip(*value_matrix))
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 588, in <listcomp>
    for col_idx, values in enumerate(zip(*value_matrix))
  File "E:\pycharm\Python\Python37\lib\concurrent\futures\process.py", line 641, in submit
    self._start_queue_management_thread()
  File "E:\pycharm\Python\Python37\lib\concurrent\futures\process.py", line 583, in _start_queue_management_thread
    self._adjust_process_count()
  File "E:\pycharm\Python\Python37\lib\concurrent\futures\process.py", line 607, in _adjust_process_count
    p.start()
  File "E:\pycharm\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "E:\pycharm\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\pycharm\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "E:\pycharm\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "E:\pycharm\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by thombashi** [comment]
@b0b5h4rp13 
Thank you for your report.

I could not reproduce the error with PowerShell.

Did you execute the program via pycharm? (from your error log)

The following modified program may workaround the issue:

```py
from simplesqlite import SimpleSQLite
import pandas


def main() -> None:
    con = SimpleSQLite("pandas_df.sqlite", max_workers=1)
    con.create_table_from_dataframe(
        pandas.DataFrame(
            [[0, 0.1, "a"], [1, 1.1, "bb"], [2, 2.2, "ccc"],], columns=["id", "value", "name"]
        ),
        table_name="pandas_df",
    )


if __name__ == "__main__":
    main()
```

**Comment by b0b5h4rp13** [comment]
putting it in a function worked great thanks again for your help!!
