### ISSUE TITLE
type conversion doen't handle datetime64 in dataframe

### ISSUE THREAD

**Issue by b0b5h4rp13** [thombashi/SimpleSQLite#67]
I am getting a "ValueError: value must be an integer, received <class 'str'> for year" when I have a dataframe with datetime64 in it.

-------------------------------- to recreate, run this
```
from simplesqlite import SimpleSQLite
import pandas as pd

def test_func():
    con = SimpleSQLite("pandas_df.sqlite")
    df = pd.DataFrame(
        [
            ['2020-03-25 15:24:00-04:00', 0, 0.1, "a"],
            ['2020-03-25 15:25:00-04:00', 1, 1.1, "bb"],
            ['2020-03-25 15:30:00-04:00', 2, 2.2, "ccc"],
        ],
        columns=['timestamp', 'id', 'value', 'name'])
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    con.create_table_from_dataframe(df,table_name="pandas_df")

if __name__ == '__main__' :
    test_func()

```
-------------------------------------  error message
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "E:\pycharm\Python\Python37\lib\concurrent\futures\process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 710, in _to_dp_list_helper
    extractor._to_dp_list(data_list, type_hint=type_hint, preprocessor=preprocessor),
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 621, in _to_dp_list
    strict_level_map=strict_level_map,
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 525, in __to_dp
    data, type_hint=type_hint, preprocessor=preprocessor, strict_level_map=strict_level_map
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 551, in __to_dp_raw
    east_asian_ambiguous_width=self.east_asian_ambiguous_width,
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_dataproperty.py", line 177, in __init__
    data, no_ansi_escape_data = preprocessor.preprocess(data)
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_preprocessor.py", line 70, in preprocess
    self.__preprocess_data(data, self.strip_str),
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_preprocessor.py", line 96, in __preprocess_string
    data = data.replace("\t", " " * self.tab_length)
  File "pandas\_libs\tslibs\timestamps.pyx", line 918, in pandas._libs.tslibs.timestamps.Timestamp.replace
  File "pandas\_libs\tslibs\timestamps.pyx", line 913, in pandas._libs.tslibs.timestamps.Timestamp.replace.validate
ValueError: value must be an integer, received <class 'str'> for year
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:/pycharm/webull/venv/apps/sql test.py", line 22, in <module>
    test_func()
  File "E:/pycharm/webull/venv/apps/sql test.py", line 18, in test_func
    con.create_table_from_dataframe(df,table_name="pandas_df")
  File "E:\pycharm\webull\venv\lib\site-packages\simplesqlite\core.py", line 1526, in create_table_from_dataframe
    index_attrs,
  File "E:\pycharm\webull\venv\lib\site-packages\simplesqlite\core.py", line 1714, in __create_table_from_tabledata
    table_data, primary_key, add_primary_key_column
  File "E:\pycharm\webull\venv\lib\site-packages\simplesqlite\core.py", line 1659, in __extract_attr_descs_from_tabledata
    for col, value_type in sorted(self.__extract_col_type_from_tabledata(table_data).items()):
  File "E:\pycharm\webull\venv\lib\site-packages\simplesqlite\core.py", line 1687, in __extract_col_type_from_tabledata
    for col_idx, col_dp in enumerate(table_data.column_dp_list)
  File "E:\pycharm\webull\venv\lib\site-packages\tabledata\_core.py", line 190, in column_dp_list
    return self.__dp_extractor.to_column_dp_list(self.value_dp_matrix)
  File "E:\pycharm\webull\venv\lib\site-packages\tabledata\_core.py", line 179, in value_dp_matrix
    to_value_matrix(self.headers, self.rows)
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 453, in to_dp_matrix
    return self.__to_dp_matrix_mt(value_matrix)
  File "E:\pycharm\webull\venv\lib\site-packages\dataproperty\_extractor.py", line 592, in __to_dp_matrix_mt
    col_idx, value_dp_list = future.result()
  File "E:\pycharm\Python\Python37\lib\concurrent\futures\_base.py", line 428, in result
    return self.__get_result()
  File "E:\pycharm\Python\Python37\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
ValueError: value must be an integer, received <class 'str'> for year

**Comment by b0b5h4rp13** [comment]
it seems that pandas doesn't read timezones in JSON.. I will have to make a creation via code example.. I will work on it today, more to come.....

**Comment by thombashi** [comment]
@b0b5h4rp13 
Thank you for your report.

I believe `SimpleSQLite 1.1.0` had fixed the problem.
Please upgrade the package and re-execute the program.

**Comment by b0b5h4rp13** [comment]
once i deleted all the pycaches,  it worked!!!  thanks for your help, saved me some time reinventing the wheel.
